In [2]:
import pandas as pd

In [4]:
import numpy as np

In [6]:
df=pd.read_csv('/content/Salary_dataset.csv')
df

Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [8]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [10]:
df.tail()

Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [36]:
x=df['YearsExperience']
y=df['Salary'].values
x

0      1.2
1      1.4
2      1.6
3      2.1
4      2.3
5      3.0
6      3.1
7      3.3
8      3.3
9      3.8
10     4.0
11     4.1
12     4.1
13     4.2
14     4.6
15     5.0
16     5.2
17     5.4
18     6.0
19     6.1
20     6.9
21     7.2
22     8.0
23     8.3
24     8.8
25     9.1
26     9.6
27     9.7
28    10.4
29    10.6
Name: YearsExperience, dtype: float64

In [15]:
y=df['Salary'].values
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [17]:
y=df.iloc[:,-1].values
y

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [20]:
x=np.array(x)
y=np.array(y)

In [25]:
x=x.reshape(-1,1)
x

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [27]:
y=y.reshape(-1,1)
y

array([[ 39344.],
       [ 46206.],
       [ 37732.],
       [ 43526.],
       [ 39892.],
       [ 56643.],
       [ 60151.],
       [ 54446.],
       [ 64446.],
       [ 57190.],
       [ 63219.],
       [ 55795.],
       [ 56958.],
       [ 57082.],
       [ 61112.],
       [ 67939.],
       [ 66030.],
       [ 83089.],
       [ 81364.],
       [ 93941.],
       [ 91739.],
       [ 98274.],
       [101303.],
       [113813.],
       [109432.],
       [105583.],
       [116970.],
       [112636.],
       [122392.],
       [121873.]])

In [29]:
x.max()

np.float64(10.6)

In [31]:
x.min()

np.float64(1.2000000000000002)

In [33]:
x_min=x.min()
x_max=x.max()
x_norm=(x-x_min)/(x_max-x_min)
x_norm

array([[0.        ],
       [0.0212766 ],
       [0.04255319],
       [0.09574468],
       [0.11702128],
       [0.19148936],
       [0.20212766],
       [0.22340426],
       [0.22340426],
       [0.27659574],
       [0.29787234],
       [0.30851064],
       [0.30851064],
       [0.31914894],
       [0.36170213],
       [0.40425532],
       [0.42553191],
       [0.44680851],
       [0.5106383 ],
       [0.5212766 ],
       [0.60638298],
       [0.63829787],
       [0.72340426],
       [0.75531915],
       [0.80851064],
       [0.84042553],
       [0.89361702],
       [0.90425532],
       [0.9787234 ],
       [1.        ]])

In [37]:
m=np.random.randn()
c=np.random.randn()
print("Randomly initialized slope:",m)
print("Randomly initialized intercept:",c)

Randomly initialized slope: 0.0987985067885723
Randomly initialized intercept: -0.04868018750209286


In [45]:
def predict(x,m,c):
  y_pred=m*x+c
  return y_pred

In [47]:
y_pred=predict(x,m,c)
y_pred

0     0.069878
1     0.089638
2     0.109397
3     0.158797
4     0.178556
5     0.247715
6     0.257595
7     0.277355
8     0.277355
9     0.326754
10    0.346514
11    0.356394
12    0.356394
13    0.366274
14    0.405793
15    0.445312
16    0.465072
17    0.484832
18    0.544111
19    0.553991
20    0.633030
21    0.662669
22    0.741708
23    0.771347
24    0.820747
25    0.850386
26    0.899785
27    0.909665
28    0.978824
29    0.998584
Name: YearsExperience, dtype: float64

In [49]:
#Display  first 5 predictions
print("first 5 predicted values:")
print(y_pred[:5])

first 5 predicted values:
0    0.069878
1    0.089638
2    0.109397
3    0.158797
4    0.178556
Name: YearsExperience, dtype: float64


In [51]:
#Mean squared error (cost function)
def compute_cost(y,y_pred):
  n=len(y)
  cost=(1/(2*n))*np.sum((y_pred-y))** 2
  return cost

In [54]:
#Compute initial cost
cost=compute_cost(y,y_pred)
print("Initial Cost (MSE):",cost)

Initial Cost (MSE): 86648011765.34453


In [57]:
#Given parameters
m=0.0
c=0.0
#prediction
y_pred=predict(x_norm,m,c)
#cost calculation
cost=compute_cost(y,y_pred)
print("cost for m=",m,"and c=",c,"is:",cost)

cost for m= 0.0 and c= 0.0 is: 77984208216000.0


In [59]:
learning_rate=0.01 #step size for gradient
epochs=100
print("learning rate:",learning_rate)
print("no of epochs:",epochs)

learning rate: 0.01
no of epochs: 100


In [65]:
n=len(y)
n

30

In [66]:
cost_history=[]

In [67]:
#Gradient Descent loop
for epoch in range(epochs):
  #step 1:prediction
  y_pred=predict(x_norm,m,c)
  #step 2:compute predictions
  dm=(1/n)*np.sum((y_pred-y)*x_norm)
  dc=(1/n)*np.sum((y_pred-y))
  #step 3:update parameters
  m=m-learning_rate*dm
  c=c-learning_rate*dc
  #step 4:Compute and store cost
  cost=compute_cost(y,y_pred)
  cost_history.append(cost)
  #print cost occasionally
  if epoch % 100==0:
    print(f"Epoch",epoch,"cost:",cost)

Epoch 0 cost: 13163220867994.402


In [69]:
def predict_salary(years_experience, m, c, X_min, X_max):
  # Normalize the single input years_experience
  normalized_years_experience = (years_experience - X_min) / (X_max - X_min)
  # Predict using the normalized value and the learned parameters
  salary_pred = m * normalized_years_experience + c
  return salary_pred

In [70]:
years=5
predicted_salary=predict_salary(years, final_slope, final_intercept, X_min, X_max)
print("predicted salary for", years, "years of experience:", predicted_salary)

NameError: name 'final_slope' is not defined